USE Academy2

CREATE TABLE Teachers (
	TeacherID INT PRIMARY KEY IDENTITY(1,1),
	EmploymentDate DATE NOT NULL CHECK(EmploymentDate >= '1990-01-01'),
	IsAssistant BIT NOT NULL DEFAULT 0,
	IsProfessor BIT NOT NULL DEFAULT 0,
	TeacherName NVARCHAR(MAX) NOT NULL DEFAULT 'Name',
	Surname NVARCHAR(MAX) NOT NULL DEFAULT 'Surname',
	Position NVARCHAR(MAX) NOT NULL DEFAULT 'Position',
	Premium MONEY NOT NULL DEFAULT 0 CHECK(Premium >= 0),
	Salary MONEY NOT NULL CHECK(Salary > 0)
)