insert into Subjects (SubjectName) values ('Smartphones');
insert into Subjects (SubjectName) values ('OS X');
insert into Subjects (SubjectName) values ('Team Leadership');
insert into Subjects (SubjectName) values ('Vector NTI');
insert into Subjects (SubjectName) values ('VJ');
insert into Subjects (SubjectName) values ('Eclipse');
insert into Subjects (SubjectName) values ('Food Processing');
insert into Subjects (SubjectName) values ('EOS');
insert into Subjects (SubjectName) values ('Data Mining');
insert into Subjects (SubjectName) values ('Beverage Industry');
insert into Subjects (SubjectName) values ('Twitter Marketing');
insert into Subjects (SubjectName) values ('iBatis');
insert into Subjects (SubjectName) values ('Google Analytics');
insert into Subjects (SubjectName) values ('HTML Scripting');
insert into Subjects (SubjectName) values ('SRT');
insert into Subjects (SubjectName) values ('HTML5');
insert into Subjects (SubjectName) values ('Loan Servicing');
insert into Subjects (SubjectName) values ('Electronic Payments');
insert into Subjects (SubjectName) values ('Mental Health');
insert into Subjects (SubjectName) values ('VGA');
