USE Academy

CREATE TABLE Subjects (
	id INT PRIMARY KEY IDENTITY,
	SubjectName NVARCHAR(100) NOT NULL DEFAULT 'SubjectName' UNIQUE
);

CREATE TABLE Teachers (
	id INT PRIMARY KEY IDENTITY,
	TeacherName NVARCHAR(MAX) NOT NULL DEFAULT 'Teacher"s name',
	TeacherSurname NVARCHAR(MAX) NOT NULL DEFAULT 'Teacher"s surname',
	Salary MONEY NOT NULL CHECK(Salary > 0)
);

CREATE TABLE Faculties (
	id INT PRIMARY KEY IDENTITY,
	FacultyName NVARCHAR(100) NOT NULL DEFAULT 'FacultyName' UNIQUE
);

CREATE TABLE Departments (
	id INT PRIMARY KEY IDENTITY,
	Financing MONEY NOT NULL DEFAULT 0 CHECK(Financing >= 0),
	DepartmentName NVARCHAR(100) NOT NULL DEFAULT 'DepartmentName' UNIQUE,
	FacultyID INT NOT NULL FOREIGN KEY REFERENCES Faculties(id)
);

CREATE TABLE Groups (
	id INT PRIMARY KEY IDENTITY,
	GroupName NVARCHAR(100) NOT NULL DEFAULT 'GroupName' UNIQUE,
	GroupYear INT NOT NULL CHECK (GroupYear > 0 AND GroupYear <= 5),
	DepartmentID INT NOT NULL FOREIGN KEY REFERENCES Departments(id)
)

CREATE TABLE Lectures(
	id INT PRIMARY KEY IDENTITY,
	LectureRoom NVARCHAR(MAX) NOT NULL DEFAULT 'LectureRoom',
	SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subjects(id),
	TeacherID INT NOT NULL FOREIGN KEY REFERENCES Teachers(id)
);

CREATE TABLE GroupLectures (
	id INT PRIMARY KEY IDENTITY,
	LDayOfWeek INT NOT NULL CHECK (LDayOfWeek > 0 AND LDayOfWeek <= 7),
	GroupID INT NOT NULL FOREIGN KEY REFERENCES Groups(id),
	LectureID INT NOT NULL FOREIGN KEY REFERENCES Lectures(id)
)

