insert into Subjects (Name) values ('Smartphones');
insert into Subjects (Name) values ('OS X');
insert into Subjects (Name) values ('Team Leadership');
insert into Subjects (Name) values ('Vector NTI');
insert into Subjects (Name) values ('VJ');
insert into Subjects (Name) values ('Eclipse');
insert into Subjects (Name) values ('Food Processing');
insert into Subjects (Name) values ('EOS');
insert into Subjects (Name) values ('Data Mining');
insert into Subjects (Name) values ('Beverage Industry');
insert into Subjects (Name) values ('Twitter Marketing');
insert into Subjects (Name) values ('iBatis');
insert into Subjects (Name) values ('Google Analytics');
insert into Subjects (Name) values ('HTML Scripting');
insert into Subjects (Name) values ('SRT');
insert into Subjects (Name) values ('HTML5');
insert into Subjects (Name) values ('Loan Servicing');
insert into Subjects (Name) values ('Electronic Payments');
insert into Subjects (Name) values ('Mental Health');
insert into Subjects (Name) values ('VGA');
