USE Academy3

CREATE TABLE LectureRooms (
	Id INT PRIMARY KEY IDENTITY,
	Building INT CHECK (Building BETWEEN 1 AND 5),
	Name NVARCHAR(10) NOT NULL DEFAULT 'LectureRoomName' UNIQUE
)

CREATE TABLE Subjects (
	Id INT PRIMARY KEY IDENTITY(1,1) ,
	Name NVARCHAR(100) NOT NULL DEFAULT 'SubjectName' UNIQUE
)

CREATE TABLE Teachers (
	Id INT PRIMARY KEY IDENTITY(1,1),	
	TeacherName NVARCHAR(max) NOT NULL DEFAULT 'TeacherName' ,
	TeacherSurname NVARCHAR(max) NOT NULL DEFAULT 'TeacherSurname'
)

CREATE TABLE Lectures (
	Id INT PRIMARY KEY IDENTITY,
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id) ,
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id) 
)

CREATE TABLE Schedules (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Class INT NOT NULL CHECK (Class BETWEEN 1 AND 8),
	SDayOFWeek INT NOT NULL CHECK (SDayOFWeek BETWEEN 1 AND 7),
	SWeek INT  NOT NULL CHECK (SWeek BETWEEN 1 AND 52),
	LectureId INT NOT NULL FOREIGN KEY REFERENCES Lectures(Id) ,
	LectureRoomId INT NOT NULL FOREIGN KEY REFERENCES LectureRooms(Id) 
)

CREATE TABLE Assistants (
	Id INT PRIMARY KEY IDENTITY(1,1),
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
)

CREATE TABLE Deans (
	Id INT PRIMARY KEY IDENTITY(1,1),
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
)

CREATE TABLE Curators (
	Id INT PRIMARY KEY IDENTITY(1,1),
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
)

CREATE TABLE Heads (
	Id INT PRIMARY KEY IDENTITY(1,1),
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id)
)

CREATE TABLE Faculties (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Building INT NOT NULL CHECK (Building BETWEEN 1 AND 5),
	FName NVARCHAR(100) NOT NULL DEFAULT 'FacultyName' UNIQUE,
	DeanId INT NOT NULL FOREIGN KEY REFERENCES Deans(Id)
)

CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY(1,1) , 
	Building INT CHECK (Building BETWEEN 1 AND 5),
	DName NVARCHAR(100) NOT NULL DEFAULT 'DepartmentName' UNIQUE,
	FacultyId INT NOT NULL FOREIGN KEY REFERENCES Faculties(Id), 
	HeadId INT NOT NULL FOREIGN KEY REFERENCES Heads(Id)
)

CREATE TABLE Groups (
	Id INT PRIMARY KEY IDENTITY(1,1), 
	GroupName NVARCHAR(10) NOT NULL DEFAULT 'GroupName' UNIQUE, 
	GYear INT NOT NULL CHECK (GYear BETWEEN 1 AND 5),
	DepartmrntId INT FOREIGN KEY REFERENCES Departments(Id) 
)

CREATE TABLE GroupsCurators (
	Id INT PRIMARY KEY IDENTITY(1,1) , 
	CuratorId INT NOT NULL FOREIGN KEY REFERENCES Curators(Id) ,
	GroupId INT NOT NULL FOREIGN KEY REFERENCES Groups(Id)  
)

CREATE TABLE GroupsLectures (
	Id INT PRIMARY KEY IDENTITY(1,1), 
	GroupId INT NOT NULL FOREIGN KEY REFERENCES Groups(Id),
	LectureId INT NOT NULL FOREIGN KEY REFERENCES Lectures(Id) 
)


